tasks:
  clean:
    command:
      - 'bun'
      - 'exec'
      - 'rm -rf node_modules lib .cache'
    
    platform: bun
    options:
      cache: false
      allowFailure: true

  typecheck:
    command:
      - 'tsc'
      # Use incremental builds with project references
      - '--build'
      # Always use pretty output
      - '--pretty'
      # Use verbose logging to see affected projects
      - '--verbose'
    inputs:
      # Source and test files
      - 'src/**/*'
      - 'tests/**/*'
      - '.cache/**/*'
      # Type declarations
      - 'types/**/*'
      # Project configs
      - 'tsconfig.json'
      - 'tsconfig.*.json'
      # Root configs (extended from only)
      - '/tsconfig.options.json'
    outputs:
      # Matches `compilerOptions.outDir`
      - 'lib'
    deps: 
      - '^:typecheck'

  fix:
    command:
      - 'biome'
      - 'check'
      - '--write'
    inputs: 
      - 'src/**/*'
      - 'tests/**/*'
      - 'tsconfig.json'
      - 'tsconfig.*.json'
      - '/tsconfig.options.json'
    outputs: 
      - 'src/**/*'
      - 'tests/**/*'
    deps: 
      - '^:typecheck'