name: 'Pipeline2'
on:
  push:
    branches:
      - 'master'
  pull_request:
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        index: [0, 1]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
      - uses: mi4uu/setup-moon-toolchain@0.0.0.2
        with:
          auto-install: true
      - run: 'moon ci --job ${{ matrix.index }} --jobTotal 2'
      - uses: 'moonrepo/run-report-action@v1'
        if: success() || failure()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: appthrust/moon-ci-retrospect@v1
        if: success() || failure()